---
title: "Pre-course self reflection (SR #1)"
author: "Zach Loo"
date: 2026-01-09
---

::: {.callout-note}
*For the full assignment description and grading specifications, please see the course website: <https://eds-240-data-viz.github.io/course-materials/assignments/SR1-precourse.html>*
:::

## Outline your learning goals & plan: 

  - [ ] **1. Which learning goals from the syllabus are you most excited about?** 

   The first goal "Identify which types of visuals are most appropriate for the data and audience" is interesting because I sometimes struggle with this. Usually in our assignments, we're told what type of plot to make with given data. When working with data on my own, I sometimes struggle with imagining what I want my final plot should look like and of course, this depends on the type of data I have. So getting better and more practice with this is cool.

  - [ ] **2. What do you hope to get out of this class?**

   Learn more niche, cool things with ggplot. We've done a lot of stuff already but I feel like there's more to learn. I'm not sure what exactly but more ggplot!

  - [ ] **3. How do you plan on accomplishing your learning goals for this course? *Note:* be specific here! Instead of writing, “I will complete homework assignments” or “I will study,” you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc.**

   I think learning as much as I can will help me a lot with these learning goals. Specificially, not just do what's needed for the assignment and but explore a bit beyond that. I can't think of a specific example but maybe like when learning and using a new function, explore the parameters that I haven't used, open the documentation, and learn what's possible beyond just what I did. This will make sure I get a little more familar with the functions we use which could be helpful in the longer run.

## (Optional) Help me get to know you better!

  - [ ] **1. Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I've been working in industry X for Y years”)?** 

    I graduated December 2024 so pretty much from undergrad, I wanted to focus in on my Environmental Science degree.

  - [ ] **2. If you have a particular career goal in mind, how does this course apply to your future career, if at all?**

    I hope I learn more tools of visualizing, expanding the ggplot toolbelt!

  - [ ] **3. What do you wish your instructors knew about you, but don't?**

    I like small group work in class!

  - [ ] **4. What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them?**

    Small group work again! It's a good break from just listening to lectures and I can talk it out with someone.

  - [ ] **5. How confident do you feel in your data visualization skills? Why?**

  7/10, pretty confident, I just think there's a lot more to learn that we haven't yet.

  - [ ] **6. How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why?** 

    7/10 again, R is a pretty straigtforward language but still there's a lot to learn. Also I find I have to search up the "Python equivalent to xyz in R" when working in R or vice versa because bilingualism.

  - [ ] **7. What have you struggled with in the past in other graduate-level courses? Why?**

    I don't really have an answer for this haha.

  - [ ] **8. Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding?**

    The modeling class seems kinda hard, I think just because the word "modeling" in the environmental/statistic context scares me a little haha.

  - [ ] **9. What responsibilities do you have outside of school, and how do you want to balance them?**

    None really! Just job searching but plan to set a little time for this per week.

  - [ ] **10. What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy?** 

    Surfing! Usually this only happens on the weekends when I go surf with other friends who drive me and our boards. I don't have a car and don't have much confidence not having a bike rack if I wanted to bike with my board.

  - [ ] **11. What is a piece of media you enjoyed recently (e.g. music, book, movie, meme)?** 

    I read the book Project Hail Mary recently because I heard it's good and the movie adaptation comes out in March. It's a really good book and the trailers for the movie look great so I'm excited!